root: ./

​structure:
    readme: README.md
    summary: SUMMARY.md​

redirects:
    validators/poa/*: validators/
    learn/governance/*: governance/
    learn/ecosystem*: intro-to-dock/ecosystem/
    learn/: intro-to-dock/
    build/*: developers-hub/